server:
  port: 8080

spring:
  application:
    name: api-gateway
  config:
    import: "optional:configserver:http://localhost:8888"
  cloud:
    gateway:
      routes:
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/order/**
        - id: inventory-service
          uri: lb://inventory-service
          predicates:
            - Path=/api/inventory/**
        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/api/payment/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
