server:
  port: 8761

spring:
  application:
    name: eureka-server
  config:
    import: "optional:configserver:http://localhost:8888"

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
